CREATE TABLE "packs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" varchar(100),
	"isPublic" boolean DEFAULT false,
	"authorId" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "packsTags" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packsTags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"packId" bigint NOT NULL,
	"tagId" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "packsUsersSubscribe" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packsUsersSubscribe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"packId" bigint NOT NULL,
	"userId" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"quest" text,
	"questImgName" text,
	"answer" text,
	"answerImgName" text,
	"hint" text,
	"exampleInText" text,
	"packId" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "questsUsers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questsUsers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"questId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"lastRepeated" timestamp,
	"NextRepeated" timestamp,
	"level" integer,
	"stage" integer
);
--> statement-breakpoint
CREATE TABLE "tags" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	CONSTRAINT "tags_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"login" varchar(50) NOT NULL,
	"passwordHash" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_login_unique" UNIQUE("login")
);
--> statement-breakpoint
ALTER TABLE "packs" ADD CONSTRAINT "packs_authorId_users_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packsTags" ADD CONSTRAINT "packsTags_packId_packs_id_fk" FOREIGN KEY ("packId") REFERENCES "public"."packs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packsTags" ADD CONSTRAINT "packsTags_tagId_tags_id_fk" FOREIGN KEY ("tagId") REFERENCES "public"."tags"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packsUsersSubscribe" ADD CONSTRAINT "packsUsersSubscribe_packId_packs_id_fk" FOREIGN KEY ("packId") REFERENCES "public"."packs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packsUsersSubscribe" ADD CONSTRAINT "packsUsersSubscribe_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quest" ADD CONSTRAINT "quest_packId_packs_id_fk" FOREIGN KEY ("packId") REFERENCES "public"."packs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questsUsers" ADD CONSTRAINT "questsUsers_questId_quest_id_fk" FOREIGN KEY ("questId") REFERENCES "public"."quest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questsUsers" ADD CONSTRAINT "questsUsers_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;