CREATE TABLE "quest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"quest" text,
	"questImgName" text,
	"answer" text,
	"answerImgName" text,
	"hint" text,
	"exampleInText" text,
	"packId" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "packs" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "packs" ALTER COLUMN "id" SET MAXVALUE 9223372036854775807;--> statement-breakpoint
ALTER TABLE "packs" ALTER COLUMN "description" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "packs" ALTER COLUMN "isPublic" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "packsTags" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "packsTags" ALTER COLUMN "id" SET MAXVALUE 9223372036854775807;--> statement-breakpoint
ALTER TABLE "packsTags" ALTER COLUMN "packId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "packsTags" ALTER COLUMN "tagId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "id" SET MAXVALUE 9223372036854775807;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET MAXVALUE 9223372036854775807;--> statement-breakpoint
ALTER TABLE "packs" ADD COLUMN "authorId" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "quest" ADD CONSTRAINT "quest_packId_packs_id_fk" FOREIGN KEY ("packId") REFERENCES "public"."packs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packs" ADD CONSTRAINT "packs_authorId_users_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;