CREATE TABLE "questsUsers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questsUsers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"questId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"lastRepeated" timestamp,
	"NextRepeated" timestamp,
	"level" integer,
	"stage" integer
);
--> statement-breakpoint
ALTER TABLE "questsUsers" ADD CONSTRAINT "questsUsers_questId_quest_id_fk" FOREIGN KEY ("questId") REFERENCES "public"."quest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questsUsers" ADD CONSTRAINT "questsUsers_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;