CREATE TABLE "packsUsersSubscribe" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packsUsersSubscribe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"packId" bigint NOT NULL,
	"userId" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "packsUsersSubscribe" ADD CONSTRAINT "packsUsersSubscribe_packId_packs_id_fk" FOREIGN KEY ("packId") REFERENCES "public"."packs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packsUsersSubscribe" ADD CONSTRAINT "packsUsersSubscribe_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;